Add Implicit cast to torch concatenation
Summary:
In PyTorch `torch.cat((TensorInt, TensorFloat))` is a valid operation, while in PopTorch it raises a `'poplar_type_error'`, this diff brings the two interfaces in line.

Fixes T59647

In addition to bringing the interfaces in line using ImplicitCast resolves user-unfriendly behaviours which seem to derive from some uninitialised outputs propagating through the `torch:jit:graph`.

One particularly bad behaviour happens when you call transpose directly after the concatenation of int and float, this causes an Abort when using a debug build and memory to explode until the OOM killer kicks in when using a Release build. A test is added for this condition called (`test_cat_transpose`), and that unsafe behaviour is defended with a new error message.

Test Plan:
### for `test_cat`

Failing tests added

```
=============================================================================== test session starts ===============================================================================
platform linux -- Python 3.6.9, pytest-6.2.1, py-1.11.0, pluggy-0.13.1 -- /localdata/alexandrep/poptorch_view/build/buildenv/bin/python
cachedir: .pytest_cache
rootdir: /localdata/alexandrep/poptorch_view/poptorch
collected 8 items

../poptorch/tests/tensor_ops_test.py::test_cat[all_floats-0] PASSED                                                                                                         [ 12%]
../poptorch/tests/tensor_ops_test.py::test_cat[all_floats-1] PASSED                                                                                                         [ 25%]
../poptorch/tests/tensor_ops_test.py::test_cat[all_ints-0] FAILED                                                                                                           [ 37%]
../poptorch/tests/tensor_ops_test.py::test_cat[all_ints-1] FAILED                                                                                                           [ 50%]
../poptorch/tests/tensor_ops_test.py::test_cat[int,float-0] FAILED                                                                                                          [ 62%]
../poptorch/tests/tensor_ops_test.py::test_cat[int,float-1] FAILED                                                                                                          [ 75%]
../poptorch/tests/tensor_ops_test.py::test_cat[float,int-0] FAILED                                                                                                          [ 87%]
../poptorch/tests/tensor_ops_test.py::test_cat[float,int-1] FAILED                                                                                                          [100%]

==================================================================================== FAILURES =====================================================================================
...
E               poptorch.poptorch_core.Error: In poptorch/python/poptorch.cpp:1391: 'poplar_type_error': Trying to concatenate tensors of different types
E               Error raised in:
E                 [0] popart::Session::prepareDevice: Poplar compilation
E                 [1] Compiler::compileAndPrepareDevice
E                 [2] LowerToPopart::compile
E                 [3] compileWithTrace

/home/alexandrep/poptorch_view/build/install/poptorch/_poplar_executor.py:569: Error
------------------------------------------------------------------------------ Captured stderr setup ------------------------------------------------------------------------------
Graph compilation:  25%|██▌       | 25/100 [00:00<00:02]
------------------------------------------------------------------------------ Captured stderr call -------------------------------------------------------------------------------

============================================================================= short test summary info =============================================================================
FAILED ../poptorch/tests/tensor_ops_test.py::test_cat[all_ints-0] - poptorch.poptorch_core.Error: In poptorch/python/poptorch.cpp:1391: 'poplar_type_error': Trying to concatena...
FAILED ../poptorch/tests/tensor_ops_test.py::test_cat[all_ints-1] - poptorch.poptorch_core.Error: In poptorch/python/poptorch.cpp:1391: 'poplar_type_error': Trying to concatena...
FAILED ../poptorch/tests/tensor_ops_test.py::test_cat[int,float-0] - poptorch.poptorch_core.Error: In poptorch/python/poptorch.cpp:1391: 'poplar_type_error': Trying to concaten...
FAILED ../poptorch/tests/tensor_ops_test.py::test_cat[int,float-1] - poptorch.poptorch_core.Error: In poptorch/python/poptorch.cpp:1391: 'poplar_type_error': Trying to concaten...
FAILED ../poptorch/tests/tensor_ops_test.py::test_cat[float,int-0] - poptorch.poptorch_core.Error: In poptorch/python/poptorch.cpp:1391: 'poplar_type_error': Trying to concaten...
FAILED ../poptorch/tests/tensor_ops_test.py::test_cat[float,int-1] - poptorch.poptorch_core.Error: In poptorch/python/poptorch.cpp:1391: 'poplar_type_error': Trying to concaten...
========================================================================== 6 failed, 2 passed in 20.78s ===========================================================================
```

All pass

### for `test_cat_transpose`

#### Test results for `test_cat_transpose` without: `ImplicitCast` or new error:

With a release build:

`158483 alexand+  20   0  0.384t 0.208t 226168 R  95.5 42.3   3:15.82 python`: note the 384GB memory usage compiling.

```
$ python -m pytest -v ../poptorch/tests/tensor_ops_test.py::test_cat_transpose
=================================================================== test session starts ====================================================================
platform linux -- Python 3.6.9, pytest-6.2.1, py-1.11.0, pluggy-0.13.1 -- /localdata/alexandrep/poptorch_view/build_release/buildenv/bin/python
cachedir: .pytest_cache
rootdir: /localdata/alexandrep/poptorch_view/poptorch
collected 2 items

../poptorch/tests/tensor_ops_test.py::test_cat_transpose[0] Killed
```

With a debug build:

```
$ python -m pytest -vs ../poptorch/tests/tensor_ops_test.py::test_cat_transpose=============================================================================== test session starts ===============================================================================
platform linux -- Python 3.6.9, pytest-6.2.1, py-1.11.0, pluggy-0.13.1 -- /localdata/alexandrep/poptorch_view/build/buildenv/bin/python
cachedir: .pytest_cache
rootdir: /localdata/alexandrep/poptorch_view/poptorch
collected 2 items

../poptorch/tests/tensor_ops_test.py::test_cat_transpose[0] python: buildenv/lib/python3.6/site-packages/torch/include/c10/util/Optional.h:730: constexpr T& c10::optional<T>::operator*() & [with T = long unsigned int]: Assertion `initialized()' failed.
Fatal Python error: Aborted

Current thread 0x00007f0c4236c740 (most recent call first):
  File "/home/alexandrep/poptorch_view/build/install/poptorch/_poplar_executor.py", line 569 in _compile
...
  File "/localdata/alexandrep/poptorch_view/build/buildenv/lib/python3.6/runpy.py", line 193 in _run_module_as_main
Aborted
```

#### Test for `test_cat_transpose` with the new error:

```
$ python -m pytest -v ../poptorch/tests/tensor_ops_test.py::test_cat_transpose
=================================================================== test session starts ====================================================================
platform linux -- Python 3.6.9, pytest-6.2.1, py-1.11.0, pluggy-0.13.1 -- /localdata/alexandrep/poptorch_view/build_release/buildenv/bin/python
cachedir: .pytest_cache
rootdir: /localdata/alexandrep/poptorch_view/poptorch
collected 2 items

../poptorch/tests/tensor_ops_test.py::test_cat_transpose[0] FAILED                                                                                   [ 50%]
../poptorch/tests/tensor_ops_test.py::test_cat_transpose[1] FAILED                                                                                   [100%]

========================================================================= FAILURES =========================================================================
....
>               self._executable = poptorch_core.compileWithTrace(*trace_args)
E               poptorch.poptorch_core.Error: In poptorch/source/popart_canonicalization/ReshapeOps.cpp:583: 'poptorch_cpp_error': Number of dimensions for tensor %56 is undefined, about to read uninitialised memory. Unexpected behaviour happened before transpose.
E               Error raised in:
E                 [0] processing %32 : Float(6, 2, strides=[1, 6], requires_grad=1, device=cpu) = aten::transpose(%56, %40, %44), scope: __module.model # /localdata/alexandrep/poptorch_view/poptorch/tests/tensor_ops_test.py:372:0
E                 [1] PopartCanonicalization
E                 [2] compileWithTrace

/home/alexandrep/poptorch_view/build_release/install/poptorch/_poplar_executor.py:569: Error
================================================================= short test summary info ==================================================================
FAILED ../poptorch/tests/tensor_ops_test.py::test_cat_transpose[0] - poptorch.poptorch_core.Error: In poptorch/source/popart_canonicalization/ReshapeOps....
FAILED ../poptorch/tests/tensor_ops_test.py::test_cat_transpose[1] - poptorch.poptorch_core.Error: In poptorch/source/popart_canonicalization/ReshapeOps....
==================================================================== 2 failed in 2.43s =====================================================================
```

#### Test for `test_cat_transpose` with `ImplicitCast`:
```
$ python -m pytest -v ../poptorch/tests/tensor_ops_test.py::test_cat_transpose
=================================================================== test session starts ====================================================================
platform linux -- Python 3.6.9, pytest-6.2.1, py-1.11.0, pluggy-0.13.1 -- /localdata/alexandrep/poptorch_view/build_release/buildenv/bin/python
cachedir: .pytest_cache
rootdir: /localdata/alexandrep/poptorch_view/poptorch
collected 2 items

../poptorch/tests/tensor_ops_test.py::test_cat_transpose[0] PASSED                                                                                   [ 50%]
../poptorch/tests/tensor_ops_test.py::test_cat_transpose[1] PASSED                                                                                   [100%]

==================================================================== 2 passed in 14.23s ====================================================================
```

Reviewers: #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, #pytorch, anthonyb

Reviewed By: #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, #pytorch, anthonyb

Subscribers: anthonyb

Maniphest Tasks: T59647

Differential Revision: https://phabricator.sourcevertex.net/D64231