Add missing 'optional' header for building on osx
Summary:
Without including the header, osx build errors with:
```
/Users/evang/dev/poponnx_view/poptorch/poptorch/source/PopartCanonicalization.cpp:30:25: error: no template named 'optional' in namespace 'std'; did you mean 'at::optional'?
  template <typename T> std::optional<T> HandleConstant(torch::jit::Node *node);
                        ^~~~~~~~~~~~~
                        at::optional
/Users/evang/dev/virtualenvs/popart/lib/python3.7/site-packages/torch/include/c10/util/Optional.h:246:7: note: 'at::optional' declared here
```

Reviewers: #pytorch, jamesn

Reviewed By: #pytorch, jamesn

Differential Revision: https://phabricator.sourcevertex.net/D26302