Fix dispatcher inplace body loops
Summary:
This diff adds the following:
- destroy dispatcher object after we are done tracing so that multiple tests (ran one after another) get correct results of `isDispatcherActive()`
- fix for loops with inplace ops in the body
- fix `JitDispatch::copyInplace` (previously we only re-wired the jit values in the mapper, now we add a `popart::identity` node to obtain a new jit value which matches the tracing behaviour)

There are still three loop tests failing after this:
```
FAILED tests/loop_test.py::test_loop_training[False] (this one should be resolved with T51159)
FAILED tests/loop_test.py::test_loop_body_inplace_ops_3[False]
FAILED tests/loop_test.py::test_loop_body_inplace_ops_4[False]
```
the last two tests are failing because we don't have support for inplace-changed graph inputs yet. As discussed, we will add support for this after merging the JIT and MLIR paths.

Reviewers: #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, #pytorch, ahmads

Reviewed By: #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, #pytorch, ahmads

Maniphest Tasks: T57408

Differential Revision: https://phabricator.sourcevertex.net/D63655