Catch and add hint to `ImportError`
Summary:
Currently users are met with the following cryptic error if they import PopTorch without having the SDK enabled:

```
[12:31:53.910] [poptorch::python] [critical] ImportError: libpvti.so: cannot open shared object file: No such file or directory

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/localdata/alexandrep/sdk-envs/poplar_sdk-ubuntu_18_04-2.5.0+924-4c870d073d/2.5.0+924_poptorch/lib/python3.6/site-packages/poptorch/__init__.py", line 29, in <module>
    import poptorch.poptorch_core as poptorch_core  # type: ignore
ImportError: libpvti.so: cannot open shared object file: No such file or directory
```

This diff replaces that with:

```
[15:34:04.337] [poptorch::python] [critical] ImportError: libpvti.so: cannot open shared object file: No such file or directory. It's possible that this was caused by importing PopTorch without an active Poplar SDK

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/localdata/harrym/envs/poplar_sdk-ubuntu_18_04-2.6.0-EA.1+966-265ae3b806/2.6.0-EA.1+966_poptorch/lib/python3.6/site-packages/poptorch/__init__.py", line 35, in <module>
    raise e
  File "/localdata/harrym/envs/poplar_sdk-ubuntu_18_04-2.6.0-EA.1+966-265ae3b806/2.6.0-EA.1+966_poptorch/lib/python3.6/site-packages/poptorch/__init__.py", line 31, in <module>
    import poptorch.poptorch_core as poptorch_core  # type: ignore
ImportError: libpvti.so: cannot open shared object file: No such file or directory. It's possible that this was caused by importing PopTorch without an active Poplar SDK
```

Reviewers: ahmads, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, #pytorch, alexandrep

Reviewed By: ahmads, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, #pytorch, alexandrep

Subscribers: alexandrep, bjornf

Maniphest Tasks: T58542

Differential Revision: https://phabricator.sourcevertex.net/D65520